# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - master

resources:
  - repo: self

variables:
  tag: '$(Build.BuildId)'
  imageRepository: 'ustpoc-docker-local.jfrog.io/pocnetcore'
  dockerFilePath: '**/Dockerfile'
  vmImageName: 'ubuntu-latest'

pool: 'Docker Pool'

stages:
  - stage: Check
    displayName: Check Stage
    jobs:
      - job: Check
        displayName: Sonar Check
        container: mcr.microsoft.com/dotnet/core/sdk:2.2
        steps:
          - task: SonarCloudPrepare@1
            inputs:
              SonarCloud: 'SonarCloud'
              organization: 'andywardust'
              scannerMode: 'MSBuild'
              projectKey: 'AndyWardUST_DotnetCoreWebApp'
              projectName: 'DotnetCoreWebApp'
              extraProperties: |
                # Additional properties that will be passed to the scanner,
                # Put one key=value per line, example:
                sonar.organization=andywardust

          - task: MSBuild@1
            inputs:
              solution: '**/*.sln'

          - task: SonarCloudAnalyze@1

          - task: SonarCloudPublish@1
            inputs:
              pollingTimeoutSec: '300'


