# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  imageRepository: 'ustpoc-docker-local.jfrog.io/pocnetcore'
  dockerFilePath: '**/Dockerfile'
  vmImageName: 'windows-latest'

pool:
  vmImage: $(vmImageName)

stages:

  - stage: Build
    displayName: Build Stage
    dependsOn: Check
    jobs:
      - job: Build
        displayName: Build
        steps:
          - task: ArtifactoryDocker@1
            inputs:
              command: 'pull'
              artifactoryService: 'jFrog'
              sourceRepo: 'docker'
              imageName: 'ustpoc-docker.jfrog.io/microsoft/dotnet:2.2-sdk'

          - task: Docker@2
            inputs:
              repository: $(imageRepository)
              command: 'build'
              Dockerfile: '$(dockerfilePath)'
              tags: '$(tag)'

          - task: UniversalPackages@0
            inputs:
              command: 'download'
              downloadDirectory: '$(System.DefaultWorkingDirectory)'
              feedsToUse: 'internal'
              vstsFeed: 'd09b6095-5d34-406d-8b60-54c555945e9a'
              vstsFeedPackage: '819e5519-79bf-4056-8920-f8c9bd51212c'
              vstsPa