# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - master

resources:
  - repo: self

pool: 'Net 31 Pool'

stages:
  - stage: Check
    displayName: Check Stage
    jobs:
      - job: Check
        displayName: Sonar Check
        steps:
          - task: UseNode@1
            inputs:
              version: '12.13.0'
              
          - task: SonarCloudPrepare@1
            inputs:
              SonarCloud: 'SonarCloud'
              organization: 'andywardust'
              scannerMode: 'MSBuild'
              projectKey: 'AndyWardUST_DotnetCoreWebApp'
              projectName: 'DotnetCoreWebApp'
              extraProperties: |
                # Additional properties that will be passed to the scanner,
                # Put one key=value per line, example:
                sonar.organization=andywardust

          - task: DotNetCoreCLI@2
            inputs:
              command: 'build'

          - task: SonarCloudAnalyze@1

          - task: SonarCloudPublish@1
            inputs:
              pollingTimeoutSec: '300'


