# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  imageRepository: 'ustpoc-docker-local.jfrog.io/pocnetcore'
  dockerFilePath: '**/Dockerfile'
  vmImageName: 'windows-latest'

pool:
  vmImage: $(vmImageName)

stages:
  - stage: Build
    displayName: Build Stage
    jobs:
      - job: Build
        displayName: Build
        steps:
          - task: ArtifactoryDocker@1
            inputs:
              command: 'pull'
              artifactoryService: 'jFrog'
              sourceRepo: 'docker'
              imageName: 'ustpoc-docker.jfrog.io/microsoft/dotnet:2.2-sdk'

          - task: Docker@2
            inputs:
              repository: $(imageRepository)
              command: 'build'
              Dockerfile: '$(dockerfilePath)'
              tags: '$(tag)'

